### ISSUE TITLE
mixin loaded too early?

### ISSUE THREAD

**Issue by berkkrkc09** [Tater-Certified/Potatoptimize#11]
Fabric 0.15.11, mixin loaded too early but should be already disabled.
```
A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'additionalentityattributes'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'additionalentityattributes'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 2 more
	Suppressed: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_156 failed
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
		at me.jellysquid.mods.sodium.client.compatibility.checks.EarlyDriverScanner.findBrokenIntelGen7GraphicsDriver(EarlyDriverScanner.java:61)
		at me.jellysquid.mods.sodium.client.compatibility.checks.EarlyDriverScanner.scanDrivers(EarlyDriverScanner.java:37)
		at me.jellysquid.mods.sodium.client.SodiumPreLaunch.onPreLaunch(SodiumPreLaunch.java:12)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(Unknown Source)
		... 3 more
	Caused by: org.spongepowered.asm.mixin.transformer.throwables.ReEntrantTransformerError: Re-entrance error.
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:283)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
		at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:75)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
		... 11 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'additionalentityattributes'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(Unknown Source)
	... 3 more
Caused by: java.lang.RuntimeException: Mixin transformation of com.llamalad7.mixinextras.MixinExtrasBootstrap failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 4 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [potatoptimize.mixins.json:memory.reduce_random.RandomCreationMixin from mod potatoptimize] from phase [DEFAULT] in config [potatoptimize.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(Unknown Source)
	... 13 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: potatoptimize.mixins.json:memory.reduce_random.RandomCreationMixin from mod potatoptimize target net.minecraft.class_5819 was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:948)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	... 19 more

```

**Comment by QPCrummer** [comment]
The mod “additionalentityattributes” seems to be incompatible with my optimization “mixin.memory.reduce_random”. For right now, just do “mixin.memory.reduce_random = false” in the config.

**Comment by berkkrkc09** [comment]
I don't have a mod named additional entity attributes. It is not in the mods folder.

**Comment by QPCrummer** [comment]
Send me the log file and I can tell you which mod that is a dependency for.

**Comment by berkkrkc09** [comment]
here's the log file: [latest.log](https://github.com/user-attachments/files/15847832/latest.log)
Just out of curiosity tho, isn't the mixin supposed to not load when disabled? 
Thanks for looking into it.

**Comment by QPCrummer** [comment]
“mythicmetals 0.19.7+1.20” is the one that has the entity attributes dependency. 

Correct, the mixin shouldn’t load if it is either disabled by default or disabled by you in the Potatoptimize config.

**Comment by berkkrkc09** [comment]
ok, thank you for your time.

**Comment by QPCrummer** [comment]
I’m going to reopen this as the issue with the mixin being loaded too early could possibly be fixed on my end at some point. It’s not a large priority, but will be fixed eventually.

**Comment by berkkrkc09** [comment]
First thanks for the clarification. 

Secondly, I Write this so the workaround is out there for anyone experiencing this. Actually, disabling Mythic Metals did not fix the issue and similar mixin errors kept being thrown with different mods so I modified [potatoptimize.mixins.json](https://github.com/user-attachments/files/15848004/potatoptimize.mixins.json) A little and it is not throwing any errors now. I believe I temporarily removed mixins from the mod?

**Comment by QPCrummer** [comment]
Yes, that will completely remove the mixin. If you disable it in the config, it should still not load the mixins in that category. 
So in the config:
mixin.memory.reduce_random = false
mixin.random.generators = false

**Comment by QPCrummer** [comment]
This issue should be fixed as `mixin.memory.reduce_random` has been removed since `mc1.21-0.0.1-dev.4`. I see no way this can cause issues anymore.

I am going to close this as resolved.
