### ISSUE TITLE
Problem with C2ME when loading a world.

### ISSUE THREAD

**Issue by Mr-Squid42** [Tater-Certified/Potatoptimize#13]
Issue with threaded entity ticking and C2ME threaded worldgen:
Description: Ticking entity

com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom$1: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: pool-11-thread-3)
This is usually NOT a bug in C2ME, but a bug in another mod or in vanilla code. 
Possible solutions: 
  - Find possible causes in the stack trace below and 
    - if caused by another mod, report this to the corresponding mod authors 
    - if no other mods are involved, report this to C2ME 
 
 (You may make this a fatal warning instead of a hard crash with fixes.enforceSafeWorldRandomAccess setting in c2me.toml)
Caused by: java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: pool-11-thread-3)
	at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.handleNotOwner(CheckedThreadLocalRandom.java:55)
	at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.isSafe(CheckedThreadLocalRandom.java:38)
	at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.method_43156(CheckedThreadLocalRandom.java:86)
	at net.minecraft.class_6566.method_43048(class_6566.java:33)
	at net.minecraft.class_4097.method_18922(net/minecraft/class_4097.java:49)
	at net.minecraft.class_4095.method_18891(me/jellysquid/mods/lithium/mixin/ai/task/launch/BrainMixin.java [lithium.mixins.json]:105)
	at net.minecraft.class_4095.method_19542(net/minecraft/class_4095.java:492)
	at net.minecraft.class_5762.method_5958(net/minecraft/class_5762.java:354)
	at net.minecraft.class_1308.method_6023(net/minecraft/class_1308.java:811)
	at net.minecraft.class_1309.method_6007(net/minecraft/class_1309.java:2778)
	at net.minecraft.class_1308.method_6007(net/minecraft/class_1308.java:572)
	at net.minecraft.class_1296.method_6007(net/minecraft/class_1296.java:128)
	at net.minecraft.class_1429.method_6007(net/minecraft/class_1429.java:57)
	at net.minecraft.class_1309.method_5773(net/minecraft/class_1309.java:2507)
	at net.minecraft.class_1308.method_5773(net/minecraft/class_1308.java:372)
	at net.minecraft.class_3218.method_18762(net/minecraft/class_3218.java:770)
	at net.minecraft.class_1937.method_18472(net/minecraft/class_1937.java:498)
	at net.minecraft.class_3218.method_31420(net/minecraft/class_3218.java:408)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3614)
	at com.github.tatercertified.potatoptimize.utils.threading.ThreadedTaskExecutor.lambda$concurrentForEach$0(ThreadedTaskExecutor.java:55)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:501)

-- Entity being ticked --
Details:
	Entity Type: minecraft:axolotl (net.minecraft.class_5762)
	Entity ID: 21
	Entity Name: Axolotl
	Entity's Exact location: 5.38, 20.27, 82.49
	Entity's Block location: World: (5,20,82), Section: (at 5,4,2 in 0,1,5; chunk contains blocks 0,-64,80 to 15,319,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:501)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3614)
	at com.github.tatercertified.potatoptimize.utils.threading.ThreadedTaskExecutor.lambda$concurrentForEach$0(ThreadedTaskExecutor.java:55)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)

**Comment by QPCrummer** [comment]
I cannot reproduce this issue. Did you by chance enable the multithreaded entities mixin in the config? This is incomplete and not meant to be used.

**Comment by Mr-Squid42** [comment]
yes

**Comment by QPCrummer** [comment]
That is the reason. That optimization is current unstable and shouldn't be enabled until it is fully completed. 

I have just updated the wiki to document all of the optimizations in Potatoptimize: https://github.com/Tater-Certified/Potatoptimize/wiki/Configuration-File
