### ISSUE TITLE
Problem with Serilum's Collective mod when loading a world

### ISSUE THREAD

**Issue by Mr-Squid42** [Tater-Certified/Potatoptimize#14]
A problem with Collective and mixin.memory.reduce_alloc:
Description: Exception in server tick loop

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1893 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at com.natamus.collective_common_fabric.data.Constants.initConstantData(Constants.java:36)
	at com.natamus.collective_common_fabric.events.CollectiveEvents.onWorldLoad(CollectiveEvents.java:52)
	at com.natamus.collective.CollectiveFabric.lambda$onInitialize$1(CollectiveFabric.java:35)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerWorldEvents.lambda$static$0(ServerWorldEvents.java:34)
	at net.minecraft.server.MinecraftServer.redirect$bme000$fabric-lifecycle-events-v1$onLoadWorld(MinecraftServer.java:4670)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:378)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:342)
	at net.minecraft.class_1132.method_3823(class_1132.java:73)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:664)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectValues()[Lnet/minecraft/class_1304; in potatoptimize.mixins.json:memory.reduce_alloc.EnchantmentsMixin from mod potatoptimize failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap potatoptimize-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 18 more

**Comment by QPCrummer** [comment]
Fixed with this version: https://modrinth.com/mod/potatoptimize/version/mc1.21-0.0.1-dev.1

**Comment by Mr-Squid42** [comment]
Thanks for this, problem is now fixed.
