### ISSUE TITLE
Random log / latest build 1.20.6

### ISSUE THREAD

**Issue by sternschnaube** [Tater-Certified/Potatoptimize#2]
Query Listener # 1/ERROR]: Caught previously unhandled exception :
Query Listener # 1/ERROR]: Query Listener # 1
java.lang.RuntimeException: Mixin transformation of com.github.tatercertified.potatoptimize.mixin.random.math.GetRandomInterface failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.minecraft.class_3364$class_3365.redirect$fgn000$potatoptimize$redirectRandomCreation(class_3364.java:515) ~[server-intermediary.jar:?]
	at net.minecraft.class_3364$class_3365.<init>(class_3364.java:337) ~[server-intermediary.jar:?]
	at net.minecraft.class_3364.method_14749(class_3364.java:230) ~[server-intermediary.jar:?]
	at net.minecraft.class_3364.method_14750(class_3364.java:117) ~[server-intermediary.jar:?]
	at net.minecraft.class_3364.run(class_3364.java:265) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for com.github.tatercertified.potatoptimize.mixin.random.math.GetRandomInterface. Mixin is defined in potatoptimize.mixins.json and cannot be referenced directly
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:334) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	... 10 more

**Comment by QPCrummer** [comment]
Can you confirm if this is still an issue with my newer versions of Potatoptimize? I have done a lot of reworking with Random and feel that this may have been accidentally fixed: https://modrinth.com/mod/potatoptimize/version/mc1.21-0.0.1-dev.5

If not, you can put `mixin.random.creation = false` in the config to fix it

**Comment by sternschnaube** [comment]
I think it should be fixed, thanks 😃
