### ISSUE TITLE
Uncompatibility crash for eplosions, 1.20.1, Really Early Dev Build 0.0.1-dev1

### ISSUE THREAD

**Issue by owosoup** [Tater-Certified/Potatoptimize#35]
crash:
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-08-23 17:23:35
Description: Ticking entity

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1927 failed
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:504)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:302)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:190)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:176)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_1937.method_46668(class_1937.java:535)
	at net.minecraft.class_3218.method_8454(class_3218.java:1053)
	at net.minecraft.class_1937.method_8437(class_1937.java:511)
	at net.minecraft.class_1548.method_7006(class_1548.java:248)
	at net.minecraft.class_1548.method_5773(class_1548.java:158)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:499)
	... 21 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector onDetonate(Lnet/minecraft/class_1937;Lnet/minecraft/class_1297;Lnet/minecraft/class_238;)Ljava/util/List; in #enhancedvisuals:enhancedvisuals.mixins.json:MixinExplosion from mod enhancedvisuals failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap enhancedvisuals.mixin.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 24 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:504)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:302)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:190)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:176)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_1937.method_46668(class_1937.java:535)
	at net.minecraft.class_3218.method_8454(class_3218.java:1053)
	at net.minecraft.class_1937.method_8437(class_1937.java:511)
	at net.minecraft.class_1548.method_7006(class_1548.java:248)
	at net.minecraft.class_1548.method_5773(class_1548.java:158)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Entity being ticked --
Details:
	Entity Type: minecraft:creeper (net.minecraft.class_1548)
	Entity ID: 54
	Entity Name: Creeper
	Entity's Exact location: -2850.85, 73.00, 898.85
	Entity's Block location: World: (-2851,73,898), Section: (at 13,9,2 in -179,4,56; chunk contains blocks -2864,-64,896 to -2849,319,911), Region: (-6,1; contains chunks -192,32 to -161,63, blocks -3072,-64,512 to -2561,319,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)

-- Affected level --
Details:
	All players: 1 total; [class_3222['{MINECRAFT_USERNAME}'/16, l='ServerLevel[New World]', x=-2850.24, y=73.42, z=894.85]]
	Chunk stats: 7851
	Level dimension: minecraft:overworld
	Level spawn location: World: (-1128,103,866), Section: (at 8,7,2 in -71,6,54; chunk contains blocks -1136,-64,864 to -1121,319,879), Region: (-3,1; contains chunks -96,32 to -65,63, blocks -1536,-64,512 to -1025,319,1023)
	Level time: 475479 game time, 66630 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: quilt
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)
```

I still haven't found the specific mod causing the issue, but it doesn't happen on its own. Maybe these logs can tell you?
If you need, I can post my mod list (~100, I know). I'm on Quilt if that matters.

**Comment by owosoup** [comment]
Found the mod, silly me, it's mentionned. [Enhancedvisuals 1.6.9](https://modrinth.com/mod/enhancedvisuals/version/kiIKJMZ6) causes the crash. The most recent version I can use, 1.8.1, also crashes.

**Comment by CreativeMD** [comment]
This mixin cannot be applied: https://github.com/CreativeMD/EnhancedVisuals/blob/1.21/src/main/java/team/creative/enhancedvisuals/mixin/ExplosionMixin.java#L18

Not sure what I can do to get around this issue. Apparently the method level.getEntities() is removed/ redirected by your mod.

**Comment by QPCrummer** [comment]
1.20.1 isn’t supported by me at the current moment.  Plus this is (as the name suggests) a very early build not intended to be compatible with most mods. The best I can suggest is to disable my explosion optimization inside of Potatoptimize config

**Comment by QPCrummer** [comment]
I may look into this at a future time, but my time is very limited currently and the majority of my focus will probably be dedicated to more recent versions of Minecraft.

**Comment by CreativeMD** [comment]
Same for me. The focus is on 1.21. Pretty sure it is the same issue there unless your code changed, because mine did not.

**Comment by owosoup** [comment]
Ok! how can I disable this in the config?
